### PR TITLE
Fix login failed toast vague message

### LINKED ISSUE #160: login failed toast should be clearer
it currently says login failed but it could be "username or password is wrong", something to that meaning

### PR DESCRIPTION
**Pull request by SelwynAng**
Resolves #160.

### CODE REVIEW

File: frontend/components/auth/login-form.tsx [hunk 1]
```diff
@@ -45,7 +45,7 @@ export function LoginForm() {
       toast({
         title: "Error",
         variant: "destructive",
-        description: "Login Failed.",
+        description: "Username or/and password provided is wrong.",
```
Comment (jq1836) [inline frontend/components/auth/login-form.tsx:48]: I think the possible error codes for the login endpoint are:
* 200
* 400 (missing fields)
* 401 (incorrect email/password)
* 500 (internal server error)

400, 401, 500 will technically be caught by this exception. Might be better to update the login function in `auth-context.tsx` to handle these different error codes.

**Review by jq1836 — APPROVED** [review]
Should technically work, assuming we call the endpoint accurately, so LGTM. I have added some suggestions for how we can improve on this to make it safer.
